#! /bin/bash  -xue

script_dir=$(readlink -f $(dirname $0))
build_script='build.sh'

rm -f ${build_script}

time  cmake ${script_dir} ; echo $?

cat << __EOF__  | tee ${build_script}
#!/bin/bash  -xue

time  make && ctest . ; echo \$?
__EOF__

chmod 755 ${build_script}
